name: Push ExDoc GitHub Pages

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest
    name: Gen docs on OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}
    strategy:
      matrix:
        otp: ["26.0"]
        elixir: ["1.17"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Cache Node Dependencies
        uses: actions/cache@v4
        id: cache
        with:
          path: |
            deps
            _build
            doc
          key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-mix-

      - name: Setup Elixir Enviornments
        uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix deps.get

      - name: Generate Docs
        if: steps.cache.outputs.cache-hit != 'true'
        run: mix docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./doc
